version: '3.8'  # Specify the version of Docker Compose

services:
  flask_app:
    build: .
    ports:
      - "3010:3010"  # Maps Flask port
    volumes:
      - .:/app  # Mounts the current directory to /app in the container
    depends_on:
      - qdrant  # Ensures Qdrant starts before Flask app
    environment:
      - QDRANT_URL=http://qdrant:6333  # Sets Qdrant URL in Flask app's environment

  qdrant:
    image: qdrant/qdrant  # Pulls the Qdrant image
    ports:
      - "6333:6333"  # Exposes Qdrant API port
      - "6334:6334"  # Exposes Qdrant Web UI port (optional)
    volumes:
      - ./qdrant_storage:/qdrant/storage:z  # Mounts a local directory for persistent Qdrant data

volumes:
  qdrant_storage:
    driver: local
